# Generated by Django 4.2.25 on 2025-11-03 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Category name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional category description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Category creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='category_created_at_idx'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this device belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.category'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['category'], name='device_category_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['category', 'status'], name='device_category_status_idx'),
        ),
    ]
